# Generated by Django 5.0.1 on 2024-01-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='name',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
