# Generated by Django 5.0.1 on 2024-01-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_uploadeddocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signing',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='document-signatures/'),
        ),
    ]
