# Generated by Django 5.0.1 on 2024-01-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_signing_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='signing',
            name='document_log_file',
            field=models.FileField(blank=True, null=True, upload_to='generated-pdfs/'),
        ),
    ]
