# Generated by Django 5.0.1 on 2024-01-18 11:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreatedDocument",
        ),
    ]
