# Generated by Django 5.0.1 on 2024-01-27 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_team_phonenumber_team_team_logo_team_website"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Unknown", max_length=500)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="uploaded_documents/"
                    ),
                ),
                ("message", models.TextField(default="Default message")),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_documents",
                        to="base.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamDocumentSigning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_signed", models.BooleanField(default=False)),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="team-document-signatures/"
                    ),
                ),
                ("signature_image_url", models.URLField(blank=True, null=True)),
                (
                    "document_log_file",
                    models.FileField(
                        blank=True, null=True, upload_to="team-generated-pdfs/"
                    ),
                ),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_signings",
                        to="base.teamdocument",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.externalrecipient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="teamdocument",
            name="team_document_signings",
            field=models.ManyToManyField(
                blank=True,
                related_name="team_signed_documents",
                through="base.TeamDocumentSigning",
                to="base.externalrecipient",
            ),
        ),
    ]
